# Generated by Django 5.0.2 on 2024-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
